# -*- coding: utf-8 -*-
"""se1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wm_pKYO2iyg2JXu4F4oLmswpoSrbm30T
"""

def weatherprediction(T, H, W):
    W = (0.5*T**2 - 0.2*H + 0.1*W - 15)

    if W > 300:
        return "sunny",W
    elif 200 < W <= 300:
        return "cloudy",W
    elif 100 < W <= 200:
        return "rainy",W
    else:
        return "stormy",W

print(weatherprediction(20, 70, 15))