# -*- coding: utf-8 -*-
"""WP~Dynamic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U54zAj-jo6EWhln7PvT0F1rA_q9aLy9W
"""

def calculate_weather_prediction(temp, humidity, wind_speed):
  weather_prediction = (0.5 * temp**2) - (0.2 * humidity) + (0.1 * wind_speed) - 15

  if weather_prediction <= 100:
    return "Stormy"
  elif 300 < weather_prediction:
    return "Sunny"
  elif 200 < weather_prediction <= 300:
    return "Cloudy"
  else:
    return "Rainy"

temp = float(input("Enter temp value (°C): "))
humidity = int(input("Enter humidity value(%): "))
wind_speed = int(input("Enter wind speed value(km/h): "))

weather_prediction = calculate_weather_prediction(temp, humidity, wind_speed)
print(f"The weather prediction is: {weather_prediction}")