# -*- coding: utf-8 -*-
"""WP~Fileaccess.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U54zAj-jo6EWhln7PvT0F1rA_q9aLy9W
"""

def W_P():
   weather=(0.5*(t**2))-(0.2*(h))+(0.1*(w)-15)
   print(weather)
   if weather<=100:
      print("The weather is stormy")
   elif weather>300:
      print("The weather is sunny")
   elif weather>200 and weather<=300:
      print("The weather is cloudy")
   elif weather>100 and weather<=200:
      print("The weather is rainy")


a=open("Weather_Prediction_Test_Cases", 'r')
test_cases = []
test_cases.append(a.readline())
b=str(test_cases[0]).split(',')
t=int(b[0])
h=int(b[1])
w=int(b[2])

W_P()