# -*- coding: utf-8 -*-
"""WP~Static.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U54zAj-jo6EWhln7PvT0F1rA_q9aLy9W
"""

def weather_forecast(air_temp,humidity_level,wind_speed):
    weather_pred=(0.5*air_temp**2-0.2*humidity_level+0.1*wind_speed-15)

    if weather_pred<=100:
      return "Strong"
    elif weather_pred>300:
      return "Sunny"
    elif 200<weather_pred<=300:
      return "Cloudy"
    else:
      return "Rainy"

print("The weather prediction will be:",weather_forecast(28,65,20))